version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "TECH:"
    groups:
      spring-boot-dependencies:
        patterns:
          - "org.springframework.boot:*"
          - "org.springframework:*"
        update-types:
          - "minor"
          - "patch"
      kotlin-dependencies:
        patterns:
          - "org.jetbrains.kotlin:*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"