version: '3.4'

services:
  postgresql:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mslibrary
      POSTGRES_PASSWORD: mslibrary
      POSTGRES_DB: mslibrary