spring:
  application:
    name: ms-library
  datasource:
    url: "jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}"
    username: "${postgres.username}"
    password: "${postgres.password}"
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          autoCreateTopics: false
          auto-add-partitions: false
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        books-out-0:
          group: ${spring.application.name}-${spring.cloud.stream.bindings.books-out-0.destination}
          destination: pub.library.books

postgres:
  host: localhost
  port: 5432
  database: mslibrary
  username: mslibrary
  password: mslibrary